---
- name: Include tasks for Debian-based systems
  include_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Include tasks for RPM-based systems
  include_tasks: rpm.yml
  when: ansible_facts['os_family'] == "RedHat"

