---
- name: Ensure DNS is configured and install Apache on RHEL 8
  hosts: 192.168.50.132
  become: yes
  tasks:
    - name: Update resolv.conf to use Google DNS
      lineinfile:
        path: /etc/resolv.conf
        state: present
        line: "nameserver 8.8.8.8"
        backup: yes

    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Start and enable Apache service
      systemd:
        name: httpd
        state: started
        enabled: yes

    - name: Ensure firewall is allowing HTTP traffic
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes
