---
- name: Security Updates Playbook with User Confirmation
  hosts: "{{ manage_node }}"
  become: yes
  tasks:

    - name: Check for available security updates
      command: dnf updateinfo list security
      register: security_updates
      changed_when: false

    - name: Display available security updates
      debug:
        msg: "{{ security_updates.stdout }}"


    - name: Apply all security updates
      dnf:
        name: "*"
        security: yes
        state: latest

    - name: Check if a reboot is required
      command: needs-restarting -r
      register: reboot_check
      failed_when: false
      changed_when: false

    - name: Notify if reboot is required
      debug:
        msg: "Reboot is required to complete updates."
      when: reboot_check.rc == 1

