---
- name: Rollback Security Updates Playbook
  hosts: all
  become: yes
  tasks:

    - name: Get the list of recently upgraded security packages
      shell: |
        dnf history list upgrades | grep -i security | awk '{print $1, $2}' 
      register: upgraded_security_packages
      changed_when: false

    - name: Display upgraded security packages
      debug:
        msg: "The following security packages were upgraded: {{ upgraded_security_packages.stdout_lines }}"

    - name: Downgrade upgraded security packages
      shell: |
        # Downgrade the package if it is part of the security update list
        dnf downgrade -y {{ item }}
      with_items: "{{ upgraded_security_packages.stdout_lines }}"
      register: rollback_result
      ignore_errors: yes

    - name: Display rollback results
      debug:
        msg: "{{ rollback_result.results }}"
