---
- name: Rollback Specific Security Updates Playbook
  hosts: all
  become: yes
  tasks:

    - name: List installed security updates
      shell: dnf updateinfo list security installed | awk '{print $1, $2}' 
      register: security_packages
      changed_when: false

    - name: Display installed security updates
      debug:
        msg: "The following security packages were updated: {{ security_packages.stdout_lines }}"

    - name: Rollback each security package to the previous version
      shell: |
        # Extract the package name and version
        pkg_name=$(echo "{{ item }}" | awk '{print $1}')
        pkg_version=$(dnf history info last | grep -i "Updated:" | grep -oP "(?<=\s)${pkg_name}.*(?=\s)" | awk '{print $2}')
        if [ -n "$pkg_version" ]; then
          dnf downgrade -y ${pkg_name}-${pkg_version}
        else
          echo "No previous version available for ${pkg_name}"
        fi
      with_items: "{{ security_packages.stdout_lines }}"
      register: rollback_result
      ignore_errors: yes

    - name: Display rollback results
      debug:
        msg: "{{ rollback_result.results }}"
