---
- name: Security Updates Playbook with User Confirmation
  hosts: all
  become: yes
  tasks:

    - name: Check for available security updates
      command: dnf updateinfo list security
      register: security_updates
      changed_when: false

    - name: Display available security updates
      debug:
        msg: "{{ security_updates.stdout }}"

    - name: Prompt for confirmation to apply updates
      pause:
        prompt: "Do you want to apply the security updates? (yes/no)"
      register: user_input

    - name: Validate user response
      fail:
        msg: "User declined to apply updates."
      when: user_input.user_input != "yes"

    - name: Apply all security updates
      dnf:
        name: "*"
        security: yes
        state: latest

    - name: Check if a reboot is required
      command: needs-restarting -r
      register: reboot_check
      failed_when: false
      changed_when: false

    - name: Notify if reboot is required
      debug:
        msg: "Reboot is required to complete updates."
      when: reboot_check.rc == 1

