---
- name: Validate and Confgure Redhat Subscription Managr
  hosts: all
  vars_files:
    - subscription_manager.yml
  tasks:
    - name: Validate repository sync
      shell: subscription-manager status
      register: repo_status
      ignore_errors: true

    - name: Print Repostatus
      debug:
        var: repo_status

    - name: Print the subscription status
      debug:
        msg: "System not register with subscription-manager"
      when: repo_status.rc != 0

    - name: Print the subscription status
      debug:
        msg: "System registered with subscription-manager"
      when: repo_status.rc == 0

    - name: Same as above but subscribe to a specific pool by ID.
      shell: subscription-manager register --username "{{ username }}" --password "{{ password }}" --auto-attach
      when: repo_status.rc != 0
