---
- name: Install Visual Studio Code
  hosts: prod
  become: yes
  tasks:
    - name: Include OS-specific role for Debian-based systems
      include_role:
        name: vscode
      when: ansible_facts['os_family'] == "Debian"

    - name: Include OS-specific role for RPM-based systems
      include_role:
        name: vscode
      when: ansible_facts['os_family'] == "RedHat"

