---
- name: Check if Java is installed
  command: "java -version"
  register: java_check
  ignore_errors: yes

- name: Install Java on Debian-based systems
  apt:
    name: "openjdk-{{ java_version }}-jdk"
    state: present
    update_cache: yes
  when: java_check.failed and ansible_os_family == "Debian"
  

- name: Install Java on RPM-based systems
  yum:
    name: "java-{{ java_version }}-openjdk"
    state: present
  when: java_check.failed and ansible_os_family == "RedHat"

