---
# tasks file for gcc
- name: Install GCC on RPM-based systems
  include_tasks: install_rpm.yml
  when: ansible_os_family == "RedHat"

- name: Install GCC on Debian-based systems
  include_tasks: install_debian.yml
  when: ansible_os_family == "Debian"

