
# handlers file for nginx
---
- name: Restart Nginx
  ansible.builtin.systemd:
    name: "{{ nginx_service_name }}"
    state: restarted

- name: Reload Nginx
  ansible.builtin.systemd:
    name: "{{ nginx_service_name }}"
    state: reloaded
...
